In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)


ModuleNotFoundError: No module named 'viz'

In [4]:
#1.
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[2, 2],
       [6, 1],
       [6, 4],
       ...,
       [3, 6],
       [4, 1],
       [4, 3]])

In [5]:
rolls

array([[2, 2],
       [6, 1],
       [6, 4],
       ...,
       [3, 6],
       [4, 1],
       [4, 3]])

In [9]:
#2.
n_flips = nrows = 100
n_coin = ncols = 8

flips = np.random.choice([0,1], n_flips * n_coin).reshape(nrows, ncols)
flips

array([[0, 1, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0],
       [1,

In [13]:
# probability of getting three heads
(flips.sum(axis=1) == 3).mean()

0.25

In [14]:
#probability of getting more than three heads
(flips.sum(axis=1) > 3).mean()

0.67

In [56]:
#3.
alumni = 0.25
n_alumni = nrows = 1_000
n_boards = ncols = 2

data = np.random.random((nrows,ncols))
data

array([[0.12953377, 0.8135948 ],
       [0.21065289, 0.6948041 ],
       [0.97271565, 0.21492641],
       ...,
       [0.11093306, 0.25020301],
       [0.60635206, 0.79718797],
       [0.57556138, 0.16261102]])

In [57]:
dataonbill = data < alumni
dataonbill

array([[ True, False],
       [ True, False],
       [False,  True],
       ...,
       [ True, False],
       [False, False],
       [False,  True]])

In [58]:
#likelyhood that both billboards will have datascientists
(dataonbill.sum(axis=1) ==2).mean()

0.067

In [76]:
#4.
popt = np.random.normal(loc=3, scale=1.5, size=1_000)
popt

array([[-0.22124636,  4.40009037,  3.20030531, ...,  2.38452376,
         3.66298401,  1.58339436],
       [ 1.0296041 ,  2.74759751,  4.81439215, ...,  2.31056789,
         0.99890327,  5.04583891],
       [ 2.91059067,  4.45824522,  0.76067502, ...,  1.10007762,
         2.79408875,  4.55386084],
       [ 3.58328302,  1.38414888,  0.41583161, ...,  4.78939923,
         3.80766968,  4.94743281],
       [ 4.81012811,  3.57255802,  4.50293254, ...,  0.91691388,
         1.55782498,  2.43906418]])

In [78]:
(popt.sum(axis=1) >= 17).mean()

1.0

5.

In [63]:
#Men
men = np.random.normal(loc=178, scale=8, size=1_000)

In [64]:
#women
women = np.random.normal(loc=170, scale=6, size=1_000)

In [69]:
#likelyhood that the woman is taller than the man
((men-women) < 0).mean()

0.204

In [53]:
#6.
achance = 0.004
nrows = 10_000
ncols = 100

data = np.random.random((nrows,ncols))
data

array([[0.11598337, 0.02121683, 0.39144881, ..., 0.08290556, 0.33461421,
        0.23068145],
       [0.74156238, 0.73721924, 0.47624484, ..., 0.61044447, 0.95918606,
        0.02987974],
       [0.63317486, 0.69512549, 0.34713767, ..., 0.65869774, 0.03072926,
        0.42351454],
       ...,
       [0.62813244, 0.1294071 , 0.19850292, ..., 0.84315162, 0.607129  ,
        0.48340558],
       [0.30643157, 0.01424749, 0.87505745, ..., 0.38481817, 0.08540296,
        0.54267052],
       [0.3658996 , 0.07792629, 0.47582813, ..., 0.14595071, 0.18617073,
        0.82350666]])

In [54]:
nissue = data < achance
nissue

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [52]:
#likley hood that one person in 50 will have issues downloading python
(nissue.sum(axis=1) >= 1).mean()

0.1791

In [55]:
#likley hood that one person in 100 will have issues downloading python
(nissue.sum(axis=1) >= 1).mean()

0.3278

In [28]:
#7.
nday = 0.7
nrows = 10_000
ncols = 3

data = np.random.random((nrows,ncols))
data

array([[0.75915893, 0.61005182, 0.09861614],
       [0.59261423, 0.69134715, 0.83563871],
       [0.16700087, 0.13349341, 0.98332877],
       ...,
       [0.83262198, 0.65251991, 0.0142339 ],
       [0.6726893 , 0.30978631, 0.27948281],
       [0.67044515, 0.57320388, 0.04578356]])

In [30]:
foodt = data > nday
foodt

array([[ True, False, False],
       [False, False,  True],
       [False, False,  True],
       ...,
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [32]:
#percentage unlikely that a food truck will not show up for three days
(foodt.sum(axis=1) == 3).mean()

0.0273

In [33]:
nday = 0.7
nrows = 10_000
ncols = 7

data = np.random.random((nrows,ncols))
data

array([[0.49235805, 0.79832789, 0.96339742, ..., 0.54404531, 0.42414486,
        0.87729532],
       [0.83086327, 0.15981251, 0.11572462, ..., 0.9634073 , 0.10348083,
        0.15894129],
       [0.70240438, 0.10142925, 0.07618643, ..., 0.33775391, 0.66992824,
        0.06196832],
       ...,
       [0.40605947, 0.71389002, 0.7986807 , ..., 0.86274216, 0.26277936,
        0.57596357],
       [0.30290423, 0.55884305, 0.29376264, ..., 0.55094707, 0.93974624,
        0.48895478],
       [0.39882285, 0.05579699, 0.25434245, ..., 0.32328869, 0.46079142,
        0.10238454]])

In [34]:
foodt = data < nday
foodt

array([[ True, False, False, ...,  True,  True, False],
       [False,  True,  True, ..., False,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       ...,
       [ True, False, False, ..., False,  True,  True],
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [35]:
#how likely a foodtruck will show up once in a week
(foodt.sum(axis=1) >= 1).mean()

0.9999

In [44]:
#8.
nbirth = 0.0027
nrows = 10_000
ncols = 40

data = np.random.random((nrows,ncols))
data

array([[0.99320164, 0.34047798, 0.02325714, ..., 0.97214892, 0.52939473,
        0.95756974],
       [0.33662686, 0.37859665, 0.58797102, ..., 0.50975395, 0.07584832,
        0.40824589],
       [0.57772002, 0.23906182, 0.22301584, ..., 0.31569268, 0.95422156,
        0.02470499],
       ...,
       [0.60459967, 0.23473937, 0.57769502, ..., 0.70660868, 0.00545674,
        0.04947924],
       [0.25388505, 0.52894859, 0.17711724, ..., 0.07467866, 0.06400128,
        0.50854343],
       [0.87545664, 0.17066011, 0.6141465 , ..., 0.40223878, 0.13526865,
        0.2200308 ]])

In [45]:
samed = data < nbirth
samed

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [40]:
#likelyhood that a group of twenty-three people and one of them will share a birthday with another
(samed.sum(axis=1) >=1).mean()

0.062

In [43]:
#likelyhood that a group of twenty people and one of them will share a birthday with another
(samed.sum(axis=1) >=1).mean()

0.051

In [46]:
#likelyhood that a group of fourty people and one of them will share a birthday with another
(samed.sum(axis=1) >=1).mean()

0.1061